

* i1820

** Sound Output Test
 https://alsa-project.org/wiki/SoundcardTesting

 Got sound working out of focusrite i1820 with alsa test tool:

 #+begin_src bash
 aplay -vv Uke2Test.wav
 #+end_src

** Sound Input Test

 Was able to record into a file using a mic

 #+begin_src bash
 arecord test.wav -r 48000 -f dat
 #+end_src

** MIDI Input Test
  Was able to receive midi input using _amidi_:

  #+begin_src bash
  [jack@jackslinuxlaptop musictools]$ amidi --list-devices
  Dir Device    Name
  IO  hw:2,0,0  Scarlett 18i20 USB MIDI 1

  [jack@jackslinuxlaptop musictools]$ amidi --port=hw:2,0,0 --dump
  90 5D 26
  90 5B 2A
  80 5D 5D
  90 59 1A
  80 5B 6F
  80 59 60
  18 bytes read
  [jack@jackslinuxlaptop musictools]$ 
  #+end_src

https://www.alsa-project.org/alsa-doc/alsa-lib/


./pcm -D default


* X11

* EGL

** Surface

   An off-screen buffer allocated by EGL.

   

* OpenGL
** What is OpenGL ES?
   This is _OpenGL for Embedded Systems_.

** What is GLEW?
   OpenGL Extension Wrangler Library (GLEW)

   Library that helps in querying and loading OpenGL extensions.

   Extensions being additional functionality provided by vendors.

   Extensions being new functions/constants.

   GLEW is used to access the modern OpenGL API functions (version 3.2 up to latest version)

   GLEW does run time loading of the OpenGL API. 

** What Options for OpenGL?
*** GLEW with Utility Library (SDL, GLUT)
*** GLFW

** GLUT
   Library used to perform system-level I/O with the host operating system.

   Functions performed include window definition, 
   window control, and monitoring of keyboard and mouse input.

   GLUT is really old and is not actively maintained.

   Carried on now by freeglut

** GLFW?
   Another utility library for use with OpenGL.

   Provides programmers with the ability to:
   create and manage windows and OpenGL contexts, handle joystick, keyboard and mouse input.
** What OpenGL versions are supported?
   #+begin_src bash
    glxinfo | grep "version"
   #+end_src

   #+begin_src c
   if(glewIsSupported("GL_VERSION_4_5"))
   printf("Supported\n");
   #+end_src
